module.exports = {
  apps: [
    {
      name: 'artist-api',
      script: './dist/server.js',
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: '1G',
      env: {
        NODE_ENV: 'development',
      },
      env_production: {
        NODE_ENV: 'production',
      },
      error_file: './logs/pm2-error.log',
      out_file: './logs/pm2-out.log',
      log_file: './logs/pm2-combined.log',
      time: true,
    },
    {
      name: 'artist-api-dev',
      script: './node_modules/.bin/ts-node',
      args: 'src/server.ts',
      exec_mode: 'fork',
      instances: 1,
      autorestart: true,
      watch: ['src'],
      ignore_watch: ['node_modules', 'logs', 'uploads'],
      max_memory_restart: '1G',
      env: {
        NODE_ENV: 'development',
      },
      error_file: './logs/pm2-dev-error.log',
      out_file: './logs/pm2-dev-out.log',
      log_file: './logs/pm2-dev-combined.log',
      time: true,
    },
    {
      name: 'flutter-web',
      script: './scripts/start-flutter-web.sh',
      exec_mode: 'fork',
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: '1G',
      error_file: './logs/pm2-flutter-error.log',
      out_file: './logs/pm2-flutter-out.log',
      log_file: './logs/pm2-flutter-combined.log',
      time: true,
    },
    {
      name: 'cloudflare-tunnel',
      script: 'cloudflared',
      args: 'tunnel --url http://localhost:9000',
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: '500M',
      env: {
        NODE_ENV: 'development',
      },
      error_file: './logs/pm2-cloudflare-error.log',
      out_file: './logs/pm2-cloudflare-out.log',
      log_file: './logs/pm2-cloudflare-combined.log',
      time: true,
    },
  ],
};
